/**
 * Takes the AST generated by the reader and condenses it into s-expressions
 */
export const makeSexprs = (ast) => {
  if (Array.isArray(ast)) {
    return ast.map(makeSexprs);
  }

  switch (ast.type) {
    case "ListPattern":
      let listValue = ast.value.map(makeSexprs);
      listValue.unshift(Symbol.for("list"));
      return listValue;

    case "HashPattern":
      let hashValue = ast.value.map(makeSexprs);
      listValue.unshift(Symbol.for("make-hash"));
      return hashValue;

    // Atoms
    case "Nil":
    case "Boolean":
    case "Number":
    case "String":
    case "Symbol":
    case "Keyword":
      return ast.value;
    default:
      throw new Error(`Unknown AST type: ${ast.type}`);
  }
};
