/**
 * Takes the AST generated by the reader and condenses it into s-expressions
 */
const makeSexprs = (ast) => {
  if (Array.isArray(ast)) {
  }

  switch (ast.type) {
    case "Nil":
    case "Boolean":
    case "Number":
    case "String":
    case "Symbol":
    case "Keyword":
      return ast.value;
    default:
      throw new Error(`Unknown AST type: ${ast.type}`);
  }
};
